### ISSUE TITLE
--keep-background removes the border & radius

### ISSUE THREAD

**Issue by Kroontje** [custom-cards/stack-in-card#1]
**Checklist:**

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser

**Release with the issue:**
current
**Last working release (if known):**

**Browser and Operating System:**
Microsoft Edge (new), Firefox and Chrome

**Description of problem:**
The borders from the theme(s) and border-radius are not applied when I use the style:
`- --keep-background: 'true'` on the 'stacked' custom button:card.
<img width="581" alt="HA-stack-in-card-border" src="https://user-images.githubusercontent.com/15806164/77406111-71435380-6db4-11ea-8db4-796a19961296.png">

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by RomRider** [comment]
Could you share the complete configuration please?

**Comment by Kroontje** [comment]
Configuration of the card you mean? Sure, here it is:

```
cards:
  - type: custom:stack-in-card
    mode: horizontal
    title: Televisie woonkamer
    cards:
      - type: vertical-stack
        cards:
          - type: "custom:button-card"
            icon: mdi:monitor
            color_type: card
            color: "#70AE98"
            color_off: rgb(245, 245, 245)
            entity: switch.harmony_tvkijken
            show_name: false
            styles:
              card:
                - --keep-background: 'true'
            tap_action:
              action: toggle
            state:
            - value: 'TV kijken'
              color: "#70AE98"
            - value: 'off'
              styles:
                icon:
                  - color: 'var(--text-color)'
          - type: conditional
            conditions:
              - entity: switch.harmony_tvkijken
                state: 'on'
            card:
              type: "custom:button-card"
              color_type: icon
              color: rgb(220, 220, 220)
              icon: mdi:volume-mute
              styles:
                card:
                  - --keep-background: 'true'
              tap_action:
                action: call-service
                service: script.mute_samsung_tv_woonkamer
                service_data:
                  entity_id: media_player.samsung_tv_woonkamer
              entity_id: media_player.samsung_tv_woonkamer
              state:
                - value: 'false'
                  styles:
                    card:
                      - color: "#F0A35E"
                      - --keep-background: 'true'
          - type: conditional
            conditions:
              - entity: switch.harmony_appletv
                state: 'on'
            card:
              type: "custom:button-card"
              color_type: icon
              color: rgb(220, 220, 220)
              icon: mdi:volume-mute
              styles:
                card:
                  - --keep-background: 'true'
              tap_action:
                action: call-service
                service: script.mute_denon_avr_x2000
                service_data:
                  entity_id: media_player.denon_avr_x2000
          - type: conditional
            conditions:
              - entity: switch.harmony_xboxone
                state: 'on'
            card:
              type: "custom:button-card"
              color_type: icon
              color: rgb(220, 220, 220)
              icon: mdi:volume-mute
              styles:
              card:
                - --keep-background: 'true'
              tap_action:
                action: call-service
                service: script.mute_denon_avr_x2000
                service_data:
                  entity_id: media_player.denon_avr_x2000
          - type: conditional
            conditions:
              - entity: switch.harmony_tvkijkenreceiver
                state: 'on'
            card:
              type: "custom:button-card"
              color_type: icon
              color: rgb(220, 220, 220)
              icon: mdi:volume-mute
              styles:
              card:
                - --keep-background: 'true'
              tap_action:
                action: call-service
                service: script.mute_denon_avr_x2000
                service_data:
                  entity_id: media_player.denon_avr_x2000
      - type: vertical-stack
        cards:
          - type: "custom:button-card"
            icon: mdi:monitor-speaker
            color_type: card
            # color: rgb(117, 189, 111)
            color: "#70AE98"
            color_off: rgb(245, 245, 245)
            entity: switch.harmony_tvkijkenreceiver
            show_name: false
            styles:
              card:
                - --keep-background: 'true'
            tap_action:
              action: toggle
            state:
            - value: 'TV kijken receiver'
              color: "#70AE98"
            - value: 'off'
              styles:
                icon:
                  - color: 'var(--text-color)'
          - type: conditional
            conditions:
              - entity: switch.harmony_tvkijken
                state: 'on'
            card:
              type: "custom:button-card"
              color_type: icon
              color: rgb(220, 220, 220)
              icon: mdi:volume-minus
              styles:
              card:
                - --keep-background: 'true'
              tap_action:
                action: call-service
                service: media_player.volume_down
                service_data:
                  entity_id: media_player.samsung_tv_woonkamer
          - type: conditional
            conditions:
              - entity: switch.harmony_appletv
                state: 'on'
            card:
              type: "custom:button-card"
              color_type: icon
              color: rgb(220, 220, 220)
              icon: mdi:volume-minus
              styles:
              card:
                - --keep-background: 'true'
              tap_action:
                action: call-service
                service: media_player.volume_down
                service_data:
                  entity_id: media_player.denon_avr_x2000
          - type: conditional
            conditions:
              - entity: switch.harmony_xboxone
                state: 'on'
            card:
              type: "custom:button-card"
              color_type: icon
              color: rgb(220, 220, 220)
              icon: mdi:volume-minus
              styles:
              card:
                - --keep-background: 'true'
              tap_action:
                action: call-service
                service: media_player.volume_down
                service_data:
                  entity_id: media_player.denon_avr_x2000
          - type: conditional
            conditions:
              - entity: switch.harmony_tvkijkenreceiver
                state: 'on'
            card:
              type: "custom:button-card"
              color_type: icon
              color: rgb(220, 220, 220)
              icon: mdi:volume-minus
              styles:
              card:
                - --keep-background: 'true'
              tap_action:
                action: call-service
                service: media_player.volume_down
                service_data:
                  entity_id: media_player.denon_avr_x2000
      - type: vertical-stack
        cards:
          - type: "custom:button-card"
            icon: mdi:apple
            color_type: card
            # color: rgb(117, 189, 111)
            color: "#70AE98"
            color_off: rgb(245, 245, 245)
            entity: switch.harmony_appletv
            show_name: false
            styles:
              card:
                - --keep-background: 'true'
            tap_action:
              action: toggle
            state:
            - value: 'Apple TV kijken'
              # color: rgb(117, 189, 111)
              color: "#70AE98"
            - value: 'off'
              styles:
                icon:
                  - color: 'var(--text-color)'
          - type: conditional
            conditions:
              - entity: switch.harmony_tvkijken
                state: 'on'
            card:
              type: "custom:button-card"
              color_type: icon
              color: rgb(220, 220, 220)
              icon: mdi:volume-plus
              styles:
              card:
                - --keep-background: 'true'
              tap_action:
                action: call-service
                service: media_player.volume_up
                service_data:
                  entity_id: media_player.samsung_tv_woonkamer
          - type: conditional
            conditions:
              - entity: switch.harmony_appletv
                state: 'on'
            card:
              type: "custom:button-card"
              color_type: icon
              color: rgb(220, 220, 220)
              icon: mdi:volume-plus
              styles:
              card:
                - --keep-background: 'true'
              tap_action:
                action: call-service
                service: media_player.volume_up
                service_data:
                  entity_id: media_player.denon_avr_x2000
          - type: conditional
            conditions:
              - entity: switch.harmony_xboxone
                state: 'on'
            card:
              type: "custom:button-card"
              color_type: icon
              color: rgb(220, 220, 220)
              icon: mdi:volume-plus
              styles:
              card:
                - --keep-background: 'true'
              tap_action:
                action: call-service
                service: media_player.volume_up
                service_data:
                  entity_id: media_player.denon_avr_x2000
          - type: conditional
            conditions:
              - entity: switch.harmony_tvkijkenreceiver
                state: 'on'
            card:
              type: "custom:button-card"
              color_type: icon
              color: rgb(220, 220, 220)
              icon: mdi:volume-plus
              styles:
              card:
                - --keep-background: 'true'
              tap_action:
                action: call-service
                service: media_player.volume_up
                service_data:
                  entity_id: media_player.denon_avr_x2000
      - type: vertical-stack
        cards:
          - type: "custom:button-card"
            icon: mdi:xbox
            color_type: card
            color: "#70AE98"
            color_off: rgb(245, 245, 245)
            entity: switch.harmony_xboxone
            show_name: false
            styles:
              card:
                - --keep-background: 'true'
            tap_action:
              action: toggle
            state:
            - value: 'Xbox One'
              color: "#70AE98"
            - value: 'off'
              styles:
                icon:
                  - color: 'var(--text-color)'
          - type: "custom:button-card"
            icon: mdi:power
            color_type: card
            color: "#CA7E8D"
            color_off: rgb(245, 245, 245)
            entity: switch.harmony_turnoff
            show_name: false
            styles:
              card:
                - --keep-background: 'true'
            tap_action:
              action: toggle
            state:
            - value: 'PowerOff'
              color: "#CA7E8D"
            - value: 'off'
              styles:
                icon:
                  - color: 'var(--text-color)'
```
This is the card:
![HA-media](https://user-images.githubusercontent.com/15806164/77624225-c496dc80-6f41-11ea-98db-0985f36ec036.png)
