### ISSUE TITLE
Box shadow and border when vertical stack is below a horizontal stack

### ISSUE THREAD

**Issue by circa1665** [custom-cards/stack-in-card#20]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
0.2.0
**Last working release (if known):**

**Browser and Operating System:**
macOS 11.1, Safari 14.0.2

**Description of problem:**
Box shadow and border when vertical stack is below a horizontal stack.

<img width="466" alt="Screenshot 2020-12-20 at 16 11 13" src="https://user-images.githubusercontent.com/33236082/102718118-5d466700-42de-11eb-9208-a90f66831c13.png">

```
type: 'custom:stack-in-card'
mode: vertical
cards:
  - type: weather-forecast
    entity: weather.openweathermap
  - type: 'custom:stack-in-card'
    mode: horizontal
    cards:
      - type: entities
        entities:
          - entity: sensor.nextsunrise
            type: 'custom:multiple-entity-row'
            show_state: false
            secondary_info:
              entity: sensor.nextsunrise
              name: false
      - type: entities
        entities:
          - entity: sensor.nextsunset
            type: 'custom:multiple-entity-row'
            show_state: false
            secondary_info:
              entity: sensor.nextsunset
              name: false
  - type: conditional
    conditions:
      - entity: sun.sun
        state: above_horizon
    card:
      type: entities
      entities:
        - entity: sensor.current_uv_level
        - entity: sensor.skin_type_2_safe_exposure_time
          name: Safe exposure time
        - entity: sensor.uv_protection_template
          name: Protection

```

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**
