### ISSUE TITLE
Too much padding between Entities and Glance Card

### ISSUE THREAD

**Issue by circa1665** [custom-cards/stack-in-card#21]
**Checklist:**

- [x ] I updated to the latest version available
- [x ] I cleared the cache of my browser

**Release with the issue:**
0.2.0
**Last working release (if known):**

**Browser and Operating System:**
macOS 11.1, Safari 14.0.2

**Description of problem:**
Too much padding between Entities and Glance card:
![Screenshot 2021-01-05 at 23 40 35](https://user-images.githubusercontent.com/33236082/103712296-55124b00-4fb1-11eb-9b1a-bc526b478394.png)

```
type: 'custom:stack-in-card'
mode: vertical
cards:
  - type: entities
    title: Bathroom
    show_header_toggle: false
    entities:
      - type: 'custom:slider-entity-row'
        entity: light.bathroom_pendant
        toggle: true
        name: Light
      - type: conditional
        conditions:
          - entity: switch.bathroom_fan_auto
            state: 'on'
        row:
          type: 'custom:multiple-entity-row'
          entity: sensor.bathroom_fan_status
          name: Fan
          show_state: false
          entities:
            - entity: sensor.bathroom_fan_status
              name: false
      - type: conditional
        conditions:
          - entity: switch.bathroom_fan_auto
            state: 'off'
        row:
          entity: switch.bathroom_fan
          name: Fan
          icon: 'mdi:fan'
      - type: 'custom:paper-buttons-row'
        buttons:
          - entity: switch.bathroom_fan_auto
            state_styles:
              'on':
                icon:
                  color: var(--state-icon-color)
                text:
                  color: var(--state-icon-color)
            state_text:
              'on': Auto
              'off': Manual
            style:
              button:
                background-color: var(--table-row-alternative-background-color)
                border-radius: 40px
      - type: section
        label: Multisensor
  - type: glance
    columns: 4
    entities:
      - entity: binary_sensor.bathroom_multisensor_motion
        name: Motion
        show_last_changed: true
      - entity: sensor.bathroom_multisensor_humidity
        name: Humidity
      - entity: sensor.bathroom_multisensor_illuminance
        name: Illuminance
      - entity: sensor.bathroom_multisensor_battery_level
        name: Battery
  - type: entities
    show_header_toggle: false
    entities:
      - type: section
        label: Climate
      - type: conditional
        conditions:
          - entity: sensor.heating_season_temp_threshold
            state: Enabled
        row:
          type: 'custom:multiple-entity-row'
          entity: climate.wiser_bathroom
          name: Heating
          show_state: false
          secondary_info:
            attribute: hvac_action
          entities:
            - entity: climate.wiser_bathroom
              attribute: current_temperature
              name: Current
              unit: °C
            - entity: climate.wiser_bathroom
              attribute: temperature
              name: Target
              unit: °C
      - type: conditional
        conditions:
          - entity: sensor.heating_season_temp_threshold
            state: Disabled
        row:
          type: 'custom:multiple-entity-row'
          entity: climate.wiser_bathroom
          attribute: current_temperature
          icon: 'mdi:thermometer'
          name: Temperature
          unit: °C
```

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**
