### ISSUE TITLE
Please help me with 2 cards

### ISSUE THREAD

**Issue by dannymertens** [custom-cards/stack-in-card#3]
Hi, I already was able to add custom cards together in one stack, but for some reason it will not work with those two cards, can someone help me with this please?

Thanks!

![image](https://user-images.githubusercontent.com/46963011/78424110-7f725900-766b-11ea-931a-ccc76ff273bb.png)

```
cards:
  - cards:
      - content: >-
          <font size="4"><font color= {{'white' if
          is_state('sensor.time_of_day','goed') else 'white'}}> 
          {{states('sensor.time_of_day')}}: Danny</font> 

          <font size="2"> [Lampen aan](/lovelace-iphone/verlichting) {% set
          lights = [
            states.light.lamp_wasruimte, states.light.ledstrip_keuken, states.light.lage_lamp,
            states.light.hoge_lamp, states.light.ledstrip_zetel, states.light.lamp_1_douche,
            states.light.lamp_2_douche, states.light.lamp_1_dressing, states.light.lamp_2_dressing,
            states.light.lamp_3_dressing, states.light.lamp_venster_hal, states.light.lamp_toilet,
            states.light.lamp_1_nachthal, states.light.lamp_2_nachthal, states.light.lamp_3_nachthal,
            states.light.lamp_4_nachthal, states.light.lamp_badkamer, states.light.lamp_1_bureau,
            states.light.lamp_1_master_slaapkamer, states.light.lamp_2_master_slaapkamer, states.light.lamp_3_master_slaapkamer,
            states.light.lamp_4_master_slaapkamer, states.light.lamp_1_terras_beneden, states.light.lamp_2_terras_beneden,
            states.light.lamp_1_terras_boven, states.light.lamp_2_terras_boven, states.light.lamp_3_terras_boven,
            states.light.lamp_4_terras_boven, states.light.lamp_5_terras_boven, states.light.lamp_6_terras_boven,
            states.light.lamp_2_bureau, states.light.lamp_3_bureau, states.light.lamp_4_bureau,
            states.light.ledstrip_bureau, states.light.lamp_michael,
            ] %} {{ lights | selectattr('state','eq','on') | list | count }} | [Deuren open](/lovelace-iphone/beveiliging) {% set Doors = [
            states.binary_sensor.achterdeur_contact_alarm,
            states.binary_sensor.voordeur_contact_alarm,
            states.binary_sensor.schuifdeur_contact_alarm,
            ] %} {{ Doors | selectattr('state','eq','on') | list | count }} | [Ramen open](/lovelace-iphone/beveiliging) {% set Windows = [
            states.binary_sensor.keukenraam_contact_alarm,
            states.binary_sensor.dubbel_raam_contact_alarm,
            states.binary_sensor.dressing_raam_contact_alarm,
            states.binary_sensor.nachthal_raam_sensor,
            states.binary_sensor.window_door_sensor,
            states.binary_sensor.badkamer_raam_sensor,
            states.binary_sensor.master_raam_sensor,
            states.binary_sensor.michael_raam_sensor,
            ] %} {{ Windows | selectattr('state','eq','on') | list | count }} </font>
        type: markdown
    type: horizontal-stack
mode: vertical
title: ''
type: 'custom:stack-in-card'
```

```
dateColor: white
name: false
dateSize: 70
dayWrapperLineColor: white
descSize: 70
dimFinishedEvents: true
entities:
  - entity: calendar.martine
  - entity: calendar.michael
  - entity: calendar.danny
  - entity: calendar.mertens_geysen
eventBarColor: white
finishedEventFilter: grayscale(100%)
finishedEventOpacity: 0.6
fullDayEventText: Dag afspraak
hoursFormat: 24
language: nl
sortByStartTime: true
locationIconColor: 'rgb(230, 124, 115)'
locationLinkColor: white
locationTextSize: 80
maxDaysToShow: 0
maxEventCount: 0
noEventsForTodayText: Geen afspraken vandaag
progressBarColor: white
showColors: true
showCurrentEventLine: false
showDescription: true
showLoader: true
showLocation: true
showMonth: false
showNoEventsForToday: true
showProgressBar: true
timeColor: white
timeSize: 80
titleColor: white
titleSize: 90
type: 'custom:atomic-calendar-revive'
untilText: Tot
showDate: false
disableEventLink: true
```
