### ISSUE TITLE
'keep: margin: false' is not respected for inserted stack

### ISSUE THREAD

**Issue by ildar170975** [custom-cards/stack-in-card#34]
**Checklist:**

- [x ] I updated to the latest version available
- [x ] I cleared the cache of my browser

**Release with the issue:**
0.2.0

**Last working release (if known):**

**Browser and Operating System:**
Chrome, Win10x64

**Description of problem:**

If the 'keep: margin: false' is set then the margin between card is supposed to be 0.
It works for two Entities cards:
```
  - type: custom:stack-in-card
    mode: vertical
    keep:
      background: true
      box_shadow: false
      margin: false
      outer_padding: false
      border_radius: false
    cards:
     - type: entities
       entities:
         - sun.sun
       card_mod:
         style: |
           ha-card {
             background-color: red;
           }
     - type: entities
       entities:
         - sun.sun
       card_mod:
         style: |
           ha-card {
             background-color: green;
           }
```
![image](https://user-images.githubusercontent.com/71872483/145307298-565f1905-235a-45b9-b80b-a27e435361d9.png)

But if the 2nd card is `stack-in-card`, then the margin is present anyway - look at the margin-top:
```
  - type: custom:stack-in-card
    mode: vertical
    keep:
      background: true
      box_shadow: false
      margin: false
      outer_padding: false
      border_radius: false
    cards:
     - type: entities
       entities:
         - sun.sun
       card_mod:
         style: |
           ha-card {
             background-color: red;
           }
     - type: custom:stack-in-card
       mode: horizontal
       keep:
         background: true
         box_shadow: false
         margin: false
         outer_padding: false
         border_radius: false
       cards:
         - type: entities
           entities:
             - sun.sun
           card_mod:
             style: |
               ha-card {
                 background-color: red;
               }
         - type: entities
           entities:
             - sun.sun
           card_mod:
             style: |
               ha-card {
                 background-color: green;
               }
```
![image](https://user-images.githubusercontent.com/71872483/145307395-e8643d5f-1b8e-4bfd-ad80-1c908266f0d0.png)

![image](https://user-images.githubusercontent.com/71872483/145307595-bce420c1-bda4-4f29-a823-a26690346e9b.png)

**Javascript errors shown in the web inspector (if applicable):**
no
```

```

**Additional information:**

**Comment by ildar170975** [comment]
And same for `border_radius: false` - it is clearly visible if you specify `margin: true`:
![image](https://user-images.githubusercontent.com/71872483/145309166-2ee1c84d-5d99-4b48-84ef-0fa22307b64f.png)

**Comment by ildar170975** [comment]
Probably same reason as here:
https://github.com/custom-cards/stack-in-card/issues/20

**Comment by ildar170975** [comment]
Seems that after 2021.12 functionality of "keep: margin: xxxx" gives erratic results if one stack includes another stack.

**Comment by BadgerLoaf** [comment]
I am seeing this problem too, where I have two horizontal stacks contained within a vertical stack.

I see this issue been open for a long time, is there a workaround or an update on the issue?

Thanks for your help!

**Comment by ildar170975** [comment]
> is there a workaround or an update on the issue?

Only by card-mod.
A required code depends on a particular case.

**Comment by BadgerLoaf** [comment]
Thanks @ildar170975, I thought that might be the case.

I've actually started trying to fix mine using ```card-mod```, as I have identified the issue in my case. Though am struggling with my skill (or lack of it!) to get the code right.

Have asked for help from the community here https://community.home-assistant.io/t/card-mod-add-css-styles-to-any-lovelace-card/120744/3799, hoping someone will be able to point me in the right direction. 

Don't suppose you have any ideas?

**Comment by ildar170975** [comment]
@BadgerLoaf 
The post you mentioned does not seem to me related to the problem.
Could you re-ask your question again in that thread?

**Comment by BadgerLoaf** [comment]
Sorry @ildar170975 if I have misunderstood something, but the issue I'm seeing is where I have two horizontal stacks within a vertical stack (using custom:stack-in-card) and this causes a gap between the two horizontal cards.

Looking at the inspect code below, I have identified that I need to replace ```display: flex``` with ```display: block``` in the ```#root``` level highlighted below. If I change this within the inspect view, it fixes the issue.
![Screenshot 2022-11-04 at 16 50 25](https://user-images.githubusercontent.com/108699847/200193900-dd712f53-74b5-45b3-9565-0d5ab0709842.png)

Is this not the same issue you were seeing? Apologies for highjacking the thread if not.

**Comment by ildar170975** [comment]
My issue can be seen here:
![изображение](https://user-images.githubusercontent.com/71872483/200201504-3ab02746-fbdb-49b5-84f8-8e0538ad63f2.png)

There is a gap between 1st top card and the 2nd bottom card (which is a horiz stack).
And this gap only occurs when the 2nd card is a stack.
So I have to remove this margin manually.
And I do it just by explicitly defining zero margins, not by changing a `display` property.

**Comment by BadgerLoaf** [comment]
Thanks @ildar170975. 

I believe we are seeing the same issue (having a horizontal stack inside a vertical one).... though sounds like you have found an easier way to get around it, than my idea of changing that display property. 

Would you mind sharing your code on how you changed to the margin to get around the issue?

**Comment by BadgerLoaf** [comment]
Hi @ildar170975 - Would you mind sharing your code as to how you removed this border? Thanks for your help!

**Comment by ildar170975** [comment]
> how you removed this border?

Sorry, I do not understand.
You are talking about a border - but this issue and my picture above are about a margin.
I have a solution for a margin only.
As for borders - I just killed them on a theme level, do not use borders at all.

**Comment by BadgerLoaf** [comment]
@ildar170975  Apologies, you are right, it's a margin issue, not the border. I didn't use the correct words.

Like you I am seeing the margin of 4px...
![Screenshot 2022-11-16 at 15 49 06](https://user-images.githubusercontent.com/108699847/202227999-ba452e46-bed4-40cc-847a-88917a8ddfc1.png)

What was your solution to remove the offending margin?

Thanks again!

**Comment by ildar170975** [comment]
Seems that `stack-in-card` is abandoned by its author and have to be fixed by card-mod.
This became worse after 2022.11.

W/o card-mod fix:
```
type: custom:stack-in-card
mode: vertical
title: title
keep:
  margin: false
  border: true
cards:
  - type: entities
    entities:
      - sun.sun
  - type: entities
    entities:
      - sun.sun
  - type: custom:stack-in-card
    mode: horizontal
    title: title
    keep:
      margin: true
      border: true
    cards:
      - type: entities
        entities:
          - sun.sun
      - type: entities
        entities:
          - sun.sun
```
![image](https://user-images.githubusercontent.com/71872483/202457919-8597f145-1836-4029-b4a2-0c894aa65759.png)

With card-mod fix:
```
type: custom:stack-in-card
mode: vertical
title: title
keep:
  margin: false
  border: true
card_mod:
  style:
    hui-vertical-stack-card $: |
      div#root > * {
        margin: 0px !important;
      }
cards:
  - type: entities
    entities:
      - sun.sun
  - type: entities
    entities:
      - sun.sun
  - type: custom:stack-in-card
    mode: horizontal
    title: title
    keep:
      margin: true
      border: true
    cards:
      - type: entities
        entities:
          - sun.sun
      - type: entities
        entities:
          - sun.sun
```
![image](https://user-images.githubusercontent.com/71872483/202458080-bead078a-652f-412c-9136-2e510cc0a13d.png)

Yes, there are still ugly round corners on the internal stack. Need to be also fixed by card-mod.

**Comment by BadgerLoaf** [comment]
@ildar170975 - Amazing, thank you! That card mod has worked and removed the gap caused by the margin.

Before:
![Screenshot 2022-11-18 at 14 56 25](https://user-images.githubusercontent.com/108699847/202733966-0011aed4-6766-45f4-9e34-1cd4121d785e.png)

After:
![Screenshot 2022-11-18 at 14 56 57](https://user-images.githubusercontent.com/108699847/202733990-5bb7788a-7f27-4d4c-a440-8306285e76b2.png)

**Comment by ildar170975** [comment]
Same problems with box-shadow & border.

**Comment by wrouesnel** [comment]
For anyone finding this, the solution for getting a clean no borders with this plugin and card mod is:

```yaml
- type: custom:stack-in-card
  title: Air Conditioners
  mode: vertical
  card_mod:
    style:
      hui-vertical-stack-card $: |
        div#root > * {
          margin: 0px !important;
          --ha-card-border-width: 0;
        }
# elided the rest of the config...
```

Before:
![image](https://github.com/custom-cards/stack-in-card/assets/772445/ab245a2e-0c07-4911-9f6c-506710b6f80d)

After:
![image](https://github.com/custom-cards/stack-in-card/assets/772445/7a125470-23c6-4ba9-a815-2a1c2d40f226)

EDIT: Probably need to tweak the paddings to get it seamless, but you get the idea.
