### ISSUE TITLE
Division when joining a vertical stack-in-card with a horizontal stack-in-card

### ISSUE THREAD

**Issue by McGiverGim** [custom-cards/stack-in-card#4]
**Checklist:**

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser

**Release with the issue:**
0.1.0

**Last working release (if known):**
Unknown

**Browser and Operating System:**
- Chrome and Windows 10
- Android and official Home Assistant app

**Description of problem:**
When adding an horizontal stack-in-card inside a vertical stack-in-card, the vertical division appears:
![image](https://user-images.githubusercontent.com/2673520/78664599-a7182a00-78d4-11ea-85bd-de0650a71214.png)

Sample of the `yaml` card of the image:
```yaml
type: 'custom:stack-in-card'
cards:
  - type: 'custom:stack-in-card'
    mode: horizontal
    cards:
      - type: sensor
        entity: sensor.boton_de_alarma_battery
        graph: line
      - type: sensor
        entity: sensor.boton_de_alarma_battery
        graph: line
  - type: sensor
    entity: sensor.boton_de_alarma_battery
    graph: line
```
**Javascript errors shown in the web inspector (if applicable):**
None

**Additional information:**
- I have played with the `keep` settings without luck.
- I can replace the horizontal stack-in-card by a standard horizontal-stack, but I want to play with the `keep` settings inside the horizontal stack (I want to add a margin and a shadow to the horizontal stack but not to the vertical stack).

**Comment by jenniferlee1818** [comment]
I have this same thing happening with my horizontal stack within vertical stack.

**Comment by julienlarivee** [comment]
Same behavior here too.

**Comment by circa1665** [comment]
Same issue:
<img width="508" alt="Screenshot 2020-12-20 at 16 03 07" src="https://user-images.githubusercontent.com/33236082/102717922-3176b180-42dd-11eb-8e81-9b4df8a903c6.png">
```
type: 'custom:stack-in-card'
mode: vertical
cards:
  - type: weather-forecast
    entity: weather.openweathermap
  - type: 'custom:stack-in-card'
    mode: horizontal
    cards:
      - type: entities
        entities:
          - entity: sensor.nextsunrise
            type: 'custom:multiple-entity-row'
            show_state: false
            secondary_info:
              entity: sensor.nextsunrise
              name: false
      - type: entities
        entities:
          - entity: sensor.nextsunset
            type: 'custom:multiple-entity-row'
            show_state: false
            secondary_info:
              entity: sensor.nextsunset
              name: false
  - type: conditional
    conditions:
      - entity: sun.sun
        state: above_horizon
    card:
      type: entities
      entities:
        - entity: sensor.current_uv_level
        - entity: sensor.skin_type_2_safe_exposure_time
          name: Safe exposure time
        - entity: sensor.uv_protection_template
          name: Protection
```
