### ISSUE TITLE
DropDowns Incompatibility with stack-in cards

### ISSUE THREAD

**Issue by sdrapha** [custom-cards/stack-in-card#40]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**

**Last working release (if known):**

**Browser and Operating System:**

**Description of problem:**

Starting on HA version  2022.3
The dropdowns don't show correclty if the `mini-media-player`[link](https://github.com/kalkih/mini-media-player) card is used inside a `custom:stack-in-card`[link](https://github.com/custom-cards/stack-in-card) or a `custom:vertical-stack-in-card` [link](https://github.com/ofekashery/vertical-stack-in-card)

![image](https://user-images.githubusercontent.com/25059996/157086282-3580a4ef-75c0-48f2-b022-58c0c3c02790.png)

I'll cross post this issue on the other involved custom cards repos, as I don't know what is the root cause for the issue.

Cross posted issues:
https://github.com/ofekashery/vertical-stack-in-card/issues/120
https://github.com/kalkih/mini-media-player/issues/631

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by mat4444** [comment]
Same issue here.
The card needs to allow overflow for the dropdown menus.
![image](https://user-images.githubusercontent.com/53400792/158390123-e0439985-711f-4401-b4a4-c1b8d4134048.png)

**Comment by guy0nabuffalo** [comment]
Also having trouble with this. Input select options do not expand past the card.

![Screenshot_20220421-063712_Home Assistant](https://user-images.githubusercontent.com/42823584/164730080-bd135407-3765-47f7-8cf7-a0b14d51147a.jpg)

**Comment by ildar170975** [comment]
The `custom:stack-in-card` is incompatible with the new Material Web Components' dropdown list control.
A very simple MWE:
```
type: custom:stack-in-card
cards:
  - type: entities
    entities:
      - entity: input_select.test_value
```
![image](https://user-images.githubusercontent.com/71872483/166166508-a5e845f1-1f2e-4f34-9042-676cbe049fa9.png)
![image](https://user-images.githubusercontent.com/71872483/166166517-8e6cc223-134f-433e-9a97-b5f96d98843d.png)
The list is clipped inside the stack's area.

Temporarily this may be fixed by applying a `overflow: visible !important;` CSS style to the stack by `card-mod`.

**Comment by sdrapha** [comment]
Thanks for the temporary work-around @ildar170975, it works.

Posting it here in a more clear format on where to use it, to make it easier for more people to use. Since card-mod css structure is not the most intuitive thing on earth.

```yaml
type: custom:stack-in-card
card_mod:
  style: |
    ha-card {
      overflow: visible !important;
    }
cards:
  - type: custom:mini-media-player
    lorem: ipsum.....
```

**Comment by ildar170975** [comment]
For the record:
This `overflow: hidden` may also cause clipping for a `history-graph`:
[described here](https://github.com/custom-cards/stack-in-card/issues/5)

![image](https://github.com/custom-cards/stack-in-card/assets/71872483/08f783fe-d818-4966-b050-d913cb1149fa)
```
type: custom:stack-in-card
cards:
  - type: history-graph
    entities:
      - sun.sun
```
