### ISSUE TITLE
Tooltip not visible if out of border

### ISSUE THREAD

**Issue by McGiverGim** [custom-cards/stack-in-card#5]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:** 
0.1.0

**Last working release (if known):**
None

**Browser and Operating System:**
Chrome and Windows 10, Android

**Description of problem:**
The tooltip of some cards (like history, for example) cuts if outside borders. This does not happen with the default `vertical-stack`
![image](https://user-images.githubusercontent.com/2673520/79422183-b24a1480-7fbc-11ea-864b-d8cbcdaaf49f.png)

**Javascript errors shown in the web inspector (if applicable):**
None

**Additional information:**

**Comment by ildar170975** [comment]
Have to confirm this.

1. Just a history-graph - tooltip is displayed properly:
```
type: history-graph
entities:
  - entity: sun.sun
hours_to_show: 72
refresh_interval: 0
```
![изображение](https://user-images.githubusercontent.com/71872483/100049348-26d51380-2e28-11eb-8a6b-fd5090931acf.png)

2. history-graph inside a vertical-stack - tooltip is displayed properly:
```
type: vertical-stack
cards:
  - type: entities
    entities:
      - sun.sun
  - type: history-graph
    entities:
      - entity: sun.sun
    hours_to_show: 72
    refresh_interval: 0
```
![изображение](https://user-images.githubusercontent.com/71872483/100049427-54ba5800-2e28-11eb-9c3a-6f5576369f94.png)

3. history-graph inside a stack-in-card - tooltip is clipped:
```
type: 'custom:stack-in-card'
cards:
  - type: entities
    entities:
      - sun.sun
  - type: history-graph
    entities:
      - entity: sun.sun
    hours_to_show: 72
    refresh_interval: 0
```
![изображение](https://user-images.githubusercontent.com/71872483/100049506-84696000-2e28-11eb-86a8-cfdf0cc38322.png)
