### ISSUE TITLE
Unable to hide border between two stacked vertical cards

### ISSUE THREAD

**Issue by mkanet** [custom-cards/stack-in-card#59]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

I am using stack-in-card to combine 2 cards _vertically_: ([Entities card](https://www.home-assistant.io/dashboards/entities/) & [Bar-card](https://github.com/custom-cards/bar-card)) . However, it's not completely seamless. There’s a divider between the 2 cards.

**Note:** bar-card entities in the below screenshot are currently hidden. I configured bar-card to hide entities that are 0.0 in value (see my card code below).

**Screenshot:**
![image](https://github.com/custom-cards/stack-in-card/assets/811008/2054d371-e197-442e-8ec3-3325e57d409f)

Below is the card code I'm using.  I need help with card-mod to hide the border shown above.

```yaml
type: custom:stack-in-card
mode: vertical
cards:
  - type: entities
    title: iGPU
    entities:
      - entity: sensor.cpu_gt_core_temperature
        name: Core Temperature
      - entity: sensor.gpu_d3d_memory_dynamic_memory
        name: Dynamic RAM
  - type: custom:bar-card
    severity:
      - from: '0'
        to: '0'
        hide: true
      - from: '1'
        to: '40'
        color: '#007A00'
      - from: '41'
        to: '90'
        color: '#EA9000'
      - from: '91'
        to: '100'
        color: '#C41400'
    entities:
      - entity: sensor.gpu_d3d_usage
        name: iGPU Usage
      - entity: sensor.gpu_video_decode_0_usage
        name: Video Decoder 0
      - entity: sensor.gpu_video_decode_1_usage
        name: Video Decoder 1
      - entity: sensor.gpu_video_processing_0_usage
        name: Video Encoder 0
      - entity: sensor.gpu_video_processing_1_usage
        name: Video Encoder 1
```
