### ISSUE TITLE
Borders not removed from Mushroom Cards in Vertical Stack

### ISSUE THREAD

**Issue by WorldOfMaze** [custom-cards/stack-in-card#60]
**Checklist:**

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser

**Release with the issue:**
Stack in Card v0.2.0; Home Assistant 2023.8.1

**Last working release (if known):**
New installation of Stack in Card

**Browser and Operating System:**
Firefox 115.0.2 on Windows 11
Home Assistant Companion App on Android 14

**Description of problem:**
When combining a Mushroom Climate Card and a Mushroom Entity Card into a vertical stack, the borders of both Mushroom cards are not hidden as expected.

![image](https://github.com/custom-cards/stack-in-card/assets/8455132/89b6c465-3600-4294-a73e-d05c6982cffd)

The YAML for this card is:

```
type: custom:stack-in-card
mode: vertical
cards:
  - type: custom:mushroom-climate-card
    entity: climate.master_bedroom
    name: Master Bedroom Thermostat
    hvac_modes:
      - heat_cool
      - heat
      - cool
      - 'off'
    show_temperature_control: true
    collapsible_controls: true
    fill_container: false
  - type: custom:mushroom-entity-card
    entity: sensor.master_bedroom_humidity
    name: Humidity
```

**Javascript errors shown in the web inspector (if applicable):**

```
card custom:stack-in-card Error: There is no cards parameter defined
    setConfig stack-in-card.js:204
    r create-element-base.ts:97
    h create-element-base.ts:111
    h create-element-base.ts:215
    c create-element-base.ts:172
    k create-card-element.ts:101
    value hui-stack-card.ts:102
    _cards hui-stack-card.ts:47
    value hui-stack-card.ts:46
    r create-element-base.ts:97
    h create-element-base.ts:140
    h create-element-base.ts:238
    c create-element-base.ts:172
    k create-card-element.ts:101
    value hui-stack-card.ts:102
    _cards hui-stack-card.ts:47
    value hui-stack-card.ts:46
    value hui-card-preview.ts:63
    performUpdate reactive-element.ts:1331
    scheduleUpdate reactive-element.ts:1263
    _$Ej reactive-element.ts:1235
[create-element-base.ts:182:12](https://raw.githubusercontent.com/home-assistant/frontend/20230802.0/src/panels/lovelace/create-element/create-element-base.ts)
    c create-element-base.ts:182
    k create-card-element.ts:101
    value hui-stack-card.ts:102
    _cards hui-stack-card.ts:47
    value hui-stack-card.ts:46
    r create-element-base.ts:97
    h create-element-base.ts:140
    h create-element-base.ts:238
    c create-element-base.ts:172
    k create-card-element.ts:101
    value hui-stack-card.ts:102
    _cards hui-stack-card.ts:47
    value hui-stack-card.ts:46
    value hui-card-preview.ts:63
    performUpdate reactive-element.ts:1331
    scheduleUpdate reactive-element.ts:1263
    _$Ej reactive-element.ts:1235
```

**Additional information:**
