### ISSUE TITLE
2024.3: Margins between cards became not controllable

### ISSUE THREAD

**Issue by ildar170975** [custom-cards/stack-in-card#66]
**Checklist:**

- [ x ] I updated to the latest version available
- [ x ] I cleared the cache of my browser

**Release with the issue:** 0.2.0

**Last working release (if known):**

**Browser and Operating System:** Chrome 122.0.6261.112 , Win10

**Description of problem:**

In 2024.3 was changed a code for stacks in HA.
Probably because of this in `stack-in-card` margin between cards became always set independently on a value of `keep`::`margin`.

Consider a code:
```
type: custom:stack-in-card
keep:
  margin: false
  background: true
cards:
  - &ref_card
    type: button
    entity: sun.sun
    card_mod:
      style: |
        ha-card {background: red;}
  - *ref_card
 ```
![image](https://github.com/custom-cards/stack-in-card/assets/71872483/c945d878-6a3d-48ed-b821-131697d1ff0e)

<!-
-
Explain what the issue is, and how things should look/behave. If possible provide a screenshot with a description.
-->

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**
