### ISSUE TITLE
core Markdown card results in

### ISSUE THREAD

**Issue by Mariusthvdb** [custom-cards/stack-in-card#7]
**Checklist:**

- [ ] I updated to the latest version available
- [ ] I cleared the cache of my browser

**Release with the issue:**
0.1.0
**Last working release (if known):**
not sure
**Browser and Operating System:**
Chrome on Mac,  Safari on Mac

**Description of problem:**

no matter how I configure the top markdown card in the stack, inspector always show below error on this Lovelace config:
```
type: custom:stack-in-card
cards:
  - type: markdown
    title: |
      Home Assistant --> Google Assistant
      Voice commands
    style: |
      ha-card {background: url('/local/various/google_assistant.png');
               background-size: cover;
               --keep-background: true;}
    content: |

      Ok/Hey Google,
      --> <i>'activity/mode'</i> <b>activeren</b>
      --> <b>turn-on/off</b> <i>'switch/verlichting'</i>
      --> <i>'switch/verlichting'</i> <b>in-/uitschakelen</b>
  - type: entities
    show_header_toggle: false
    entities:
   etc etc
```
**Javascript errors shown in the web inspector (if applicable):**

```

```
safari:
<img width="555" alt="Schermafbeelding 2020-04-23 om 13 27 53" src="https://user-images.githubusercontent.com/33354141/80094336-59ebb780-8566-11ea-8aa4-7d9f4f059bb2.png">

chrome:
<img width="739" alt="Schermafbeelding 2020-04-23 om 13 29 03" src="https://user-images.githubusercontent.com/33354141/80094377-6ff97800-8566-11ea-9109-d5c6ac11394d.png">

**Additional information:**
thought the errors doesnt seem to point to stack-in-card, Ive been able to positively identify this to only happen on the view with this markdown bit in the config. also see community post: 
https://community.home-assistant.io/t/frontend-error-on-logfile/41519/26?u=mariusthvdb

**Comment by Mariusthvdb** [comment]
update:

same goes for the stack-in-card with a picture-entity card:
```
  - type: custom:stack-in-card
    cards:
#      - type: picture-entity
#        entity: light.kantoor_lights
#        name: Kantoor
#        image: /local/images/kantoor.png
#        state_filter:
#          'off': grayscale(72%)
#        tap_action:
#          action: toggle
#        hold_action:
#          action: more-info
      - type: glance
        entities:
          - entity: light.office_inside
            tap_action:
              action: toggle
          - entity: light.bureau_left
            tap_action:
              action: toggle
          - entity: light.bureau_right
            tap_action:
              action: toggle
          - entity: light.office_outside
            tap_action:
              action: toggle
```

without comments, this config results in the mentioned error in the title, when commented , the view shows 100% error free.
