### ISSUE TITLE
Displaying borders

### ISSUE THREAD

**Issue by ganjakyp-hub** [custom-cards/stack-in-card#71]
In version 0.2.0 the boundaries between entityes are displayed, how can I hide them?

```
type: custom:stack-in-card
title: Освещение
mode: vertical
keep:
  outer_padding: false
cards:
  - type: entities
    entities:
      - entity: switch.gostinaia_switch_1
      - entity: switch.gostinaia_switch_2
  - type: custom:stack-in-card
    mode: horizontal
    keep:
      box_shadow: false   
    cards:
      - type: button
        entity: sun.sun
      - type: button
        entity: sun.sun
```

![Image](https://github.com/user-attachments/assets/f2c471cc-c80d-4b5e-ab9c-de88ffe58650)
